{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<div class="block">

{if ne( $attribute_base, 'ContentObjectAttribute' )}
    {def $id_base = concat( 'ezcoa-', $attribute_base, '-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
{else}
    {def $id_base = concat( 'ezcoa-', $attribute.contentclassattribute_id, '_', $attribute.contentclass_attribute_identifier )}
{/if}


    <div class="element">
        <label for="{$id_base}_hour">{'Hour'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_hour" class="hr_selector ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_time_hour_{$attribute.id}" size="3" value="{if $attribute.content.is_valid}{$attribute.content.hour}{/if}" />
    </div>

    <div class="element">
        <label for="{$id_base}_minute">{'Minute'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_minute" class="min_selector ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_time_minute_{$attribute.id}" size="3" value="{if $attribute.content.is_valid}{$attribute.content.minute}{/if}" />
    </div>

    {if $attribute.contentclass_attribute.data_int2|eq(1)}
    <div class="element">
        <label for="{$id_base}_second">{'Second'|i18n( 'design/standard/content/datatype' )}:</label>
        <input id="{$id_base}_second" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_time_second_{$attribute.id}" size="3" value="{if $attribute.content.is_valid}{$attribute.content.second}{/if}" />
    </div>
    {/if}

    <div class="element">
        <label for="{$id_base}_tz">Time Zone:</label>
        <select name="{$id_base}_tz" class='tz_selector' onchange="var myzone=$(this).val();$('.tz_selector').each(function(){ldelim}$(this).val(myzone){rdelim})">
			<option value=0>EST (GMT-5)</option>
			<option value=1>CST (GMT-6)</option>
			<option value=2>MST (GMT-7)</option>
			<option value=3>PST (GMT-8)</option>
		</select>
    </div>

    <div class="break"></div>

</div>
{/default}

{run-once}

{literal}

<script type='text/javascript'>
	
	$(function(){
		$("#editform").submit(function(){
			tz_e = $(".tz_selector:first");
			hr_ls = $("[for$=hour]");
			hr_ls.each(function(){
				hr_element = $(this).parents('.element').find('input');
				if (hr_element.val() != '') {
					var new_hour = hr_element.val() - tz_e.val();
					if (new_hour < 0) {
						var matchme = (hr_element.attr('class').indexOf('from') > 0) ? '_from' : '_to';
						date_el = $("[class*='"+matchme+"'][name^='ContentObjectAttribute_date']:first");
						dropdatebyone(date_el.parents(".block"));
						new_hour = 24 + parseInt(hr_element.val()) - tz_e.val();
					} 
					hr_element.val(new_hour);
					min_element = hr_element.parents('.block').find('.min_selector');
					if (min_element.val() == '' || min_element.val() == '0' || min_element.val() == 0) min_element.val('00');
				}
			})

		})	
	})
	
	function dropdatebyone(el_wrapper) {
		var dates = new Array();
		$(el_wrapper).find('input').each(function(){
			dates.push($(this).val());
		})
		d = new Date(dates[0], dates[1], dates[2], 0, 0, 0, 0);
		d.setDate(d.getDate() - 1);
		dates[0] = d.getFullYear();
		dates[1] = d.getMonth();
		dates[2] = d.getDate();
		loopme = $(el_wrapper).find('input');
		loopme.each(function(index, domEle){
				if (index < 3) $(domEle).val(dates[index]);
		})
	}

</script>

{/literal}

{/run-once}